name: Backend Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup
        working-directory: ./backend
        run: |
          cat <<EOF > .env
          JWT_SECRET='secret'

          DATABASE_HOST='${{ secrets.MYSQL_SERVER_DNS }}'
          DATABASE_PORT=3306
          DATABASE_USERNAME='${{ secrets.MYSQL_USERNAME }}'
          DATABASE_PASSWORD='${{ secrets.MYSQL_PASSWORD }}'
          DATABASE_SCHEMA='${{ secrets.MYSQL_DBNAME }}'

          MODE='PROD'

          환경 변수가 .env 파일에 성공적으로 작성되었습니다.
          EOF
          cat .env

      - name: backendRun
        working-directory: ./backend
        run: |
          npm install
          node setup.js

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.BACKEND_APP_NAME }}
          publish-profile: ${{ secrets.BACKEND_WEBAPP_PUBLISH_PROFILE }}
          package: .
