name: Front Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: frontRun
        working-directory: ./frontend
        run: |
          npm i
          npm rum build --if-present

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.FRONTEND_APP_NAME }}
          publish-profile: ${{ secrets.FRONTEND_WEBAPP_PUBLISH_PROFILE }}
          package: $(System.ArtifactsDirectory)/frontend
